const scenarioSelect=document.querySelector("#scenario"),description=document.querySelector("#scenario-description"),runButton=document.querySelector("#run"),runStatus=document.querySelector("#run-status"),output=document.querySelector("#run-output");
const reportPanel=document.querySelector("#report-panel"),reviewPanel=document.querySelector("#review-panel"),jiraPanel=document.querySelector("#jira-panel"),summary=document.querySelector("#summary"),reportLinks=document.querySelector("#report-links");
let scenarios=[],currentDirectory=null,currentReports=[];
const text=(value,fallback="Unavailable")=>value===null||value===undefined||value===""?fallback:String(value);
function status(label,kind){runStatus.textContent=label;runStatus.className=`status ${kind}`}
function button(label,path){const item=document.createElement("button");item.type="button";item.className="secondary";item.textContent=label;item.addEventListener("click",()=>window.bugReportApp.openPath(path));return item}
function showLinks(reports){currentReports=reports||[];reportLinks.replaceChildren();for(const path of currentReports){const name=path.split(/[\\/]/).pop();reportLinks.append(button(name,path))}}
function fillReview(review){const form=document.querySelector("#review-form");for(const [name,value] of Object.entries(review||{})){const field=form.elements.namedItem(name);if(field)field.value=value||""}}
function renderReport(data,jiraDraft,reports){reportPanel.classList.remove("hidden");reviewPanel.classList.remove("hidden");jiraPanel.classList.remove("hidden");summary.replaceChildren();const values=[["Simple test name",data.details.testTitle.split(" > ").pop()],["What went wrong",data.details.errorMessage],["Failure category",jiraDraft?"Bug":"Unknown"],["Fingerprint",data.fingerprint],["Stability",data.stability.classification],["Browser",data.environment.browserName]];for(const [label,value] of values){const card=document.createElement("div"),heading=document.createElement("span"),body=document.createElement("p");card.className="summary-card";heading.textContent=label;body.textContent=text(value);card.append(heading,body);summary.append(card)}document.querySelector("#expected").textContent=text(data.details.expectedBehavior);document.querySelector("#actual").textContent=text(data.details.actualBehavior);fillReview(data.humanReview);showLinks(reports);renderJira(jiraDraft)}
function renderJira(draft){if(!draft)return;document.querySelector("#jira-summary").value=draft.summary;document.querySelector("#jira-description").value=draft.description;document.querySelector("#screenshot-count").textContent=String(draft.screenshotPaths.length)}
async function loadScenarios(){try{scenarios=await window.bugReportApp.listScenarios();scenarioSelect.replaceChildren(...scenarios.map(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.name;return option}));updateDescription();runButton.disabled=!scenarios.length}catch(error){scenarioSelect.replaceChildren();description.textContent=`Unable to load scenarios: ${error.message}`;runButton.disabled=true}}
function updateDescription(){description.textContent=scenarios.find(item=>item.id===scenarioSelect.value)?.description||""}
scenarioSelect.addEventListener("change",updateDescription);
runButton.addEventListener("click",async()=>{runButton.disabled=true;status("Running…","running");output.textContent="The selected Playwright scenario is running…";reportPanel.classList.add("hidden");reviewPanel.classList.add("hidden");jiraPanel.classList.add("hidden");try{const result=await window.bugReportApp.runScenario(scenarioSelect.value);output.textContent=result.output||"Test finished.";currentDirectory=result.directory;if(result.data){renderReport(result.data,result.jiraDraft,result.reports);status("Failed — report ready","failed")}else if(result.passed){status("Passed","passed")}else{status("Failed — no report","failed")}}catch(error){status("Could not run","failed");output.textContent=error.message}finally{runButton.disabled=false}});
document.querySelector("#open-folder").addEventListener("click",()=>currentDirectory&&window.bugReportApp.openPath(currentDirectory));
document.querySelector("#review-form").addEventListener("submit",async event=>{event.preventDefault();if(!currentDirectory)return;const save=document.querySelector("#save-status"),form=new FormData(event.currentTarget),review=Object.fromEntries(form.entries());save.textContent="Saving and regenerating…";try{const result=await window.bugReportApp.saveReview(currentDirectory,review);const paths=[result.reports.markdown,result.reports.html,result.reports.pdf,result.reports.docx].filter(Boolean);renderReport(result.data,result.jiraDraft,paths);save.textContent="Review saved. Reports regenerated."}catch(error){save.textContent=`Could not save: ${error.message}`}});
void loadScenarios();
