import { categorize_failure } from "./fingerprint";
import { normalize_report_data } from "./bug-report-generator";
import { friendly_report_title, friendly_test_name } from "./text-utils";
import type { FailureAnalysisData } from "./types";

export function escape_html(value: unknown): string {
  return String(value ?? "Unavailable").replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
}
const show = (value: unknown) => value === null || value === undefined || value === "" ? "Unavailable" : escape_html(value);
const list = (items: string[], empty = "None captured") => items.length ? `<ul>${items.map(item => `<li>${escape_html(item)}</li>`).join("")}</ul>` : `<p class="muted">${empty}</p>`;
const evidence_links = (title: string, paths: string[]) => `<section><h3>${title}</h3>${paths.length ? `<ul>${paths.map(path => `<li><a href="${escape_html(path.replace(/\\/g, "/"))}">${escape_html(path)}</a></li>`).join("")}</ul>` : '<p class="muted">None captured</p>'}</section>`;

export function format_html(input: FailureAnalysisData, screenshotSource?: string): string {
  const data = normalize_report_data(input);
  const { details: d, evidence: e, environment: n } = data;
  const title = data.aiAnalysis?.title ?? friendly_report_title(d.errorMessage, d.testTitle, d.expectedBehavior, d.actualBehavior);
  const screenshot = screenshotSource || e.screenshotPaths[0] ? `<figure><img src="${escape_html(screenshotSource ?? e.screenshotPaths[0].replace(/\\/g, "/"))}" alt="Failure screenshot"><figcaption>Failure screenshot</figcaption></figure>` : '<p class="muted">No screenshot captured.</p>';
  const network = e.networkFailures.length ? `<table><thead><tr><th>Method</th><th>Status</th><th>URL / reason</th></tr></thead><tbody>${e.networkFailures.map(x => `<tr><td>${show(x.method)}</td><td>${show(x.status ?? "failed")}</td><td>${show(`${x.url}${x.reason ? ` - ${x.reason}` : ""}`)}</td></tr>`).join("")}</tbody></table>` : '<p class="muted">None captured</p>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape_html(title)}</title><style>
  :root{--ink:#172033;--muted:#667085;--line:#d7dce5;--accent:#3157d5;--soft:#f4f6fb}*{box-sizing:border-box}body{margin:0;color:var(--ink);font:14px/1.5 Arial,sans-serif;background:#eef1f6}main{max-width:980px;margin:24px auto;background:#fff;padding:42px 50px;box-shadow:0 2px 12px #0002}h1{font-size:28px;margin:0 0 8px}h2{font-size:19px;margin:30px 0 12px;border-bottom:2px solid var(--accent);padding-bottom:6px}h3{font-size:15px;margin:18px 0 7px}.warning{border-left:4px solid #e7a400;background:#fff8df;padding:10px 12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 20px}.meta{background:var(--soft);padding:8px 11px;border-radius:5px}.label{font-size:11px;text-transform:uppercase;color:var(--muted);font-weight:bold}.value{overflow-wrap:anywhere}table{width:100%;border-collapse:collapse}th,td{text-align:left;vertical-align:top;border:1px solid var(--line);padding:7px;overflow-wrap:anywhere}th{background:var(--soft)}img{display:block;max-width:100%;max-height:650px;object-fit:contain;margin:auto;border:1px solid var(--line)}figcaption{text-align:center;color:var(--muted);margin-top:5px}a{color:var(--accent)}.muted{color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#171d2a;color:#f8fafc;padding:14px;border-radius:5px}@media(max-width:650px){main{margin:0;padding:24px}.grid{grid-template-columns:1fr}}@media print{body{background:#fff}main{box-shadow:none;margin:0;max-width:none;padding:0}h2,h3{break-after:avoid}h2,h3,figure,table,.meta,pre{break-inside:avoid}img{max-height:55vh}a{color:inherit;text-decoration:underline}}
  </style></head><body><main><header><h1>${escape_html(title)}</h1><p class="warning">${escape_html(data.automatedWarning)}</p></header>
  <h2>Summary</h2><div class="grid">${[["Status",d.status],["Failure category",categorize_failure(d.errorMessage)],["Fingerprint",data.fingerprint],["Stability",`${data.stability.classification} (${data.stability.sampleSize} samples)`]].map(([k,v])=>`<div class="meta"><div class="label">${k}</div><div class="value">${show(v)}</div></div>`).join("")}</div><p><strong>What went wrong:</strong> ${show(d.errorMessage)}</p>
  <h2>Reproduction</h2><div class="grid"><div class="meta"><div class="label">Test</div><div class="value">${show(friendly_test_name(d.testTitle))}</div></div><div class="meta"><div class="label">Failed step</div><div class="value">${show(d.failedStep)}</div></div><div class="meta"><div class="label">Expected</div><div class="value">${show(d.expectedBehavior)}</div></div><div class="meta"><div class="label">Actual</div><div class="value">${show(d.actualBehavior)}</div></div></div><h3>Steps</h3>${d.testSteps.length ? `<ol>${d.testSteps.map(x=>`<li>${escape_html(x)}</li>`).join("")}</ol>` : '<p class="muted">Unavailable</p>'}
  <h2>Environment and CI</h2><div class="grid">${[["Browser / project",`${n.browserName} / ${n.projectName}`],["OS",`${n.operatingSystem} ${n.systemRelease}`],["Viewport",n.viewport?`${n.viewport.width} x ${n.viewport.height}`:null],["Locale / timezone",`${show(n.locale)} / ${show(n.timezone)}`],["Commit / branch",`${show(n.commitSha)} / ${show(n.branch)}`],["CI provider",n.ciProvider],["CI run",n.ciRunUrl],["Execution time",n.executionTime instanceof Date?n.executionTime.toISOString():n.executionTime]].map(([k,v])=>`<div class="meta"><div class="label">${k}</div><div class="value">${show(v)}</div></div>`).join("")}</div>
  <h2>Screenshot</h2>${screenshot}<h2>Console errors</h2>${list(e.consoleMessages)}<h2>Page errors</h2>${list(e.pageErrors)}<h2>Network errors</h2>${network}
  <h2>Evidence</h2>${evidence_links("Screenshots",e.screenshotPaths)}${evidence_links("Traces",e.tracePaths)}${evidence_links("Other attachments",e.otherAttachments)}
  <h2>Stability assessment</h2><p><strong>${escape_html(data.stability.classification)}</strong></p>${list(data.stability.observations,"Insufficient observations for a specific finding.")}
  ${data.mode === "developer" ? `<h2>Stack trace</h2><pre>${escape_html(d.stackTrace ?? "Unavailable")}</pre>` : ""}
  </main></body></html>`;
}
